/**
 * Extracts a construction schedule (PDF) into a structured list of
 * activities for the Construction track. Called from
 * /api/deals/[id]/dev-schedule/import — the result is previewed to the
 * analyst before anything is written to the DB.
 */

import Anthropic from "@anthropic-ai/sdk";

const MODEL = "claude-sonnet-4-6";

function getClient() {
  return new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
}

export interface ExtractedGcPhase {
  /** Human-readable activity name as shown to the analyst. */
  label: string;
  /**
   * Stable slug used as predecessor_key references. Generated by the
   * model — if two rows collide the importer will suffix them.
   */
  phase_key: string;
  start_date: string | null;
  duration_days: number;
  /** phase_key of the predecessor activity, or null if this is an entry point. */
  predecessor_key: string | null;
}

const SYSTEM_PROMPT = `You extract activities from construction schedule PDFs (Primavera P6, MS Project, Excel-printed gantts, etc.) into a structured JSON array.

Return JSON only, matching exactly this shape:
{
  "activities": [
    {
      "label": "<activity name as printed>",
      "phase_key": "<lowercase snake_case slug, e.g. 'foundation_pour'>",
      "start_date": "YYYY-MM-DD or null if not visible",
      "duration_days": <integer days; round durations shown in weeks/months>,
      "predecessor_key": "<phase_key of predecessor activity in this list, or null>"
    }
  ]
}

Rules:
- Preserve the original label wording — don't rename "Slab on Grade" to "Foundation".
- Use snake_case phase_keys unique within the list. If the PDF has hierarchical activity IDs (1.1, 1.2.1) you may use those verbatim as keys.
- Only include actual activities. Skip legends, header rows, subtotal/summary rows, and text like "Project Schedule v3".
- If the PDF shows dependencies (arrows, predecessor columns, finish-to-start chains), capture the primary predecessor for each row. If the only signal is visual ordering, chain each row to the one above it.
- duration_days should be the planned duration. If both start and finish are shown but no duration, compute it.
- If start_date is ambiguous (month-only, fiscal quarters), set it to null rather than guessing.

Return only the JSON object — no markdown fences, no commentary.`;

async function withRetry<T>(fn: () => Promise<T>, attempts = 2, baseDelayMs = 800): Promise<T> {
  let lastErr: unknown;
  for (let i = 0; i < attempts; i++) {
    try { return await fn(); } catch (e) {
      lastErr = e;
      if (i < attempts - 1) await new Promise((r) => setTimeout(r, baseDelayMs * (i + 1)));
    }
  }
  throw lastErr;
}

/**
 * Parse the model's JSON response robustly. Claude occasionally wraps
 * JSON in markdown fences or adds a stray prefix line even when asked
 * not to — peel those off before parsing.
 */
function parseResponse(text: string): ExtractedGcPhase[] {
  let payload = text.trim();
  if (payload.startsWith("```")) {
    payload = payload.replace(/^```(?:json)?\s*/i, "").replace(/```\s*$/, "");
  }
  // Find the first `{` so we tolerate a leading stray sentence.
  const firstBrace = payload.indexOf("{");
  if (firstBrace > 0) payload = payload.slice(firstBrace);
  const obj = JSON.parse(payload) as { activities?: unknown };
  if (!obj || !Array.isArray(obj.activities)) {
    throw new Error("Model response missing `activities` array");
  }
  const seenKeys = new Set<string>();
  const rows: ExtractedGcPhase[] = [];
  for (const raw of obj.activities) {
    if (!raw || typeof raw !== "object") continue;
    const r = raw as Record<string, unknown>;
    const label = typeof r.label === "string" ? r.label.trim() : "";
    if (!label) continue;
    let key = typeof r.phase_key === "string" && r.phase_key.trim()
      ? r.phase_key.trim().toLowerCase().replace(/[^a-z0-9_]+/g, "_").replace(/^_+|_+$/g, "")
      : label.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "");
    if (!key) key = `activity_${rows.length + 1}`;
    // De-duplicate keys by suffixing — predecessor references from the
    // model might not survive, but the analyst can fix in the preview.
    let dedup = key;
    let i = 2;
    while (seenKeys.has(dedup)) { dedup = `${key}_${i++}`; }
    seenKeys.add(dedup);

    const start = typeof r.start_date === "string" && /^\d{4}-\d{2}-\d{2}$/.test(r.start_date)
      ? r.start_date
      : null;
    const dur = typeof r.duration_days === "number" && Number.isFinite(r.duration_days)
      ? Math.max(0, Math.round(r.duration_days))
      : 0;
    const pred = typeof r.predecessor_key === "string" && r.predecessor_key.trim()
      ? r.predecessor_key.trim().toLowerCase().replace(/[^a-z0-9_]+/g, "_").replace(/^_+|_+$/g, "")
      : null;

    rows.push({
      label,
      phase_key: dedup,
      start_date: start,
      duration_days: dur,
      predecessor_key: pred,
    });
  }
  return rows;
}

/**
 * Extracts activities from a GC schedule. If `pdfBuffer` is provided,
 * the PDF is parsed server-side (pdf-parse) and the text is fed to the
 * model. Returns an empty array if extraction fails — the route
 * handler treats that as a user-visible "no activities found" state.
 */
export async function extractGcSchedule(pdfBuffer: Buffer): Promise<ExtractedGcPhase[]> {
  let rawText = "";
  try {
    const pdfParse = (await import("pdf-parse")).default;
    const parsed = await pdfParse(pdfBuffer);
    rawText = (parsed.text || "").replace(/\x00/g, "").replace(/[�]/g, "");
  } catch (e) {
    console.error("gc-schedule-extract: pdf-parse failed:", e);
    return [];
  }
  if (!rawText.trim()) return [];

  // Very long schedules get truncated — the model can't ingest arbitrary
  // PDF text and most P6 prints have the activity list in the first
  // several thousand tokens anyway.
  const MAX_CHARS = 60_000;
  const text = rawText.length > MAX_CHARS ? rawText.slice(0, MAX_CHARS) : rawText;

  const client = getClient();
  const result = await withRetry(async () => {
    const res = await client.messages.create({
      model: MODEL,
      max_tokens: 8192,
      system: SYSTEM_PROMPT,
      messages: [
        {
          role: "user",
          content: `Extract the activities from this construction schedule:\n\n${text}`,
        },
      ],
    });
    const block = res.content.find((b) => b.type === "text");
    if (!block || block.type !== "text") throw new Error("No text in model response");
    return block.text;
  });

  try {
    return parseResponse(result);
  } catch (e) {
    console.error("gc-schedule-extract: JSON parse failed:", e);
    return [];
  }
}
