/**
 * Types for the IC Package system.
 *
 * An IC Package is a structured, data-driven investment committee briefing
 * rendered as editorial-quality HTML (and exportable to PDF). Numbers come
 * from the deal's existing underwriting record; prose is generated by
 * Claude and editable in-place.
 */

export type ScenarioVariant = "upside" | "base" | "downside";
export type MetricVariant = "default" | "stabilized";

export interface MastheadProps {
  dealName: string;
  italicWord: string | null;
  kicker: string;
  dealCode: string;
  dealSubtitle: string;
  preparedDate: string;
}

export interface ExecBoxProps {
  label: string;
  headlineHtml: string;
  bodyHtml: string;
}

export interface MetricCell {
  label: string;
  value: string;
  note: string;
  variant?: MetricVariant;
}

export interface SectionHeadProps {
  number: string;
  headlineHtml: string;
  tag: string;
}

export interface ThesisCard {
  pill: string;
  headlineHtml: string;
  bodyHtml: string;
}

export interface ScenarioStat {
  label: string;
  value: string;
}

export interface Scenario {
  variant: ScenarioVariant;
  label: string;
  headlineHtml: string;
  narrativeHtml: string;
  stats: ScenarioStat[];
}

export interface CapitalSource {
  name: string;
  type: string;
  terms: string;
  amount: number;
  percentage: number;
}

export interface BusinessPhase {
  headlineHtml: string;
  bodyHtml: string;
}

export interface RiskFactor {
  name: string;
  descriptionHtml: string;
}

export interface CalloutProps {
  label: string;
  bodyHtml: string;
}

/**
 * A fully-resolved IC Package ready to render. Numbers come from the deal
 * mapper; prose (anything ending in `Html`) comes from the prose generator
 * or human edits.
 */
export interface IcPackage {
  masthead: MastheadProps;
  exec: ExecBoxProps;
  metrics: MetricCell[];
  sections: {
    marketThesis: {
      head: SectionHeadProps;
      proseHtml: string;
      thesisCards: ThesisCard[];
      callouts: CalloutProps[];
    };
    capitalStack: {
      head: SectionHeadProps;
      sources: CapitalSource[];
      proseHtml: string;
    };
    scenarios: {
      head: SectionHeadProps;
      introHtml: string;
      scenarios: Scenario[];
      callouts: CalloutProps[];
    };
    businessPlan: {
      head: SectionHeadProps;
      phases: BusinessPhase[];
    };
    risks: {
      head: SectionHeadProps;
      blockHeadlineHtml: string;
      blockSubtitle: string;
      risks: RiskFactor[];
    };
    ask: {
      head: SectionHeadProps;
      paragraphsHtml: string[];
    };
  };
  footer: {
    dealCode: string;
    brandLeft: string;
    brandRight: string;
  };
}

/**
 * Structured deal context handed to the Claude prose generator. Numbers
 * only — the LLM uses them to craft specific, concrete prose rather than
 * hedged generic copy.
 */
export interface DealContext {
  dealName: string;
  propertyType: string;
  location: string;
  purchasePrice: number | null;
  goingInCap: number | null;
  stabilizedYOC: number | null;
  leveredIRR: number | null;
  equityMultiple: number | null;
  holdPeriod: number | null;
  pricePerUnit: number | null;
  unitCount: number | null;
  squareFootage: number | null;
  yearBuilt: number | null;
  investmentStrategy: string | null;
  capitalStack: CapitalSource[];
  marketContext?: string;
  sellerContext?: string;
  businessPlanSummary?: string;
  customNotes?: string;
  /**
   * Compressed snapshot of the deal's development schedule
   * (`deal_dev_phases`) so the prose generator can cite specific
   * timeline + budget facts in the IC narrative. Server-side merged in
   * the generate route — clients don't need to populate this.
   */
  scheduleSummary?: {
    totalBudget: number;
    earliestStart: string | null;
    latestEnd: string | null;
    tracks: Array<{
      track: "acquisition" | "development" | "construction";
      label: string;
      phaseCount: number;
      startDate: string | null;
      endDate: string | null;
      durationDays: number | null;
      totalBudget: number;
      pctComplete: number;
      milestones: Array<{
        label: string;
        startDate: string | null;
        endDate: string | null;
        durationDays: number | null;
        pctComplete: number;
        budget: number | null;
      }>;
    }>;
  };
}

/**
 * The prose the generator returns. Field names mirror the IC package
 * sections — the mapper merges this with numeric props to produce the
 * final IcPackage.
 */
export interface ProseSections {
  execHeadlineHtml: string;
  execBodyHtml: string;
  marketThesisHtml: string;
  thesisCards: ThesisCard[];
  businessPlan: BusinessPhase[];
  risks: RiskFactor[];
  callouts: CalloutProps[];
  askParagraphsHtml: string[];
  scenarios: Scenario[];
}
